api_platform:
    allow_plain_identifiers: true
    mapping:
        paths: ['%kernel.project_dir%/src/Domain']
    swagger:
        versions: [2]
    formats:
        json:
            mime_types: [ 'application/json' ]
