nelmio_api_doc:
    documentation:
        info:
            title: PollingAPI
            description: api for polls
            version: 1.0.0
    areas: # to filter documented areas
        default:
            path_patterns: [ ^/api ]
            host_patterns: [ ^api\. ]
        polling:
            path_patterns:
                - '^/polling'